codecov:
  token: "af82c8d0-6782-403d-9549-82ad4bea1602"
  
  ignore:
  - "src/main/java/br/com/api/config"
  - "src/main/java/br/com/api/controller/handler"
  - "src/main/java/br/com/api/controller/handler/resource"
  - "src/main/java/br/com/api/exception"
  - "src/main/java/br/com/api/user/dto"
  - "src/main/java/br/com/api/user/model"
  - "src/main/java/br/com/api/user/repository"
  - "src/main/java/br/com/api/user/resource"
