codecov:
  token: af82c8d0-6782-403d-9549-82ad4bea1602
ignore:
  - "src/main/java/br/com/api/ApiServiceApplication.java"
  - "src/main/java/br/com/api/config/swagger/SwaggerConfig.java"
  - "src/main/java/br/com/api/config/security/ApplicationConfig.java"
  - "src/main/java/br/com/api/config/security/SimpleCORSFilter.java"
  - "src/main/java/br/com/api/config/security/WebConfig.java"
  - "src/main/java/br/com/api/config/security/WebSecurityConfig.java"
  - "src/main/java/br/com/api/config/rest/RestTemplateConfig.java"
  - "src/main/java/br/com/api/config/rabbitmq/RabbitConfig.java"
  - "src/main/java/br/com/api/config/jwt/JwtAuthEntryPoint.java"
  - "src/main/java/br/com/api/config/jwt/JwtAuthTokenFilter.java"
  - "src/main/java/br/com/api/config/jwt/JwtBlacklist.java"
  - "src/main/java/br/com/api/config/jwt/JwtProvider.java"
  - "src/main/java/br/com/api/exception/EmailNotFoundException.java"
  - "src/main/java/br/com/api/exception/ExistingEmailException.java"
  - "src/main/java/br/com/api/exception/IllegalRoleException.java"
  - "src/main/java/br/com/api/exception/Sha512Exception.java"
  - "src/main/java/br/com/api/user/dto/LoginDTO.java"
  - "src/main/java/br/com/api/user/dto/RegisterDTO.java"
  - "src/main/java/br/com/api/user/UserDTO.java"
  - "src/main/java/br/com/api/user/model/AccessToken.java"
  - "src/main/java/br/com/api/user/model/Role.java"
  - "src/main/java/br/com/api/user/model/TokenEntity.java"
  - "src/main/java/br/com/api/user/model/User.java"
  - "src/main/java/br/com/api/user/repository/RoleRepository.java"
  - "src/main/java/br/com/api/user/repository/TokenRepository.java"
  - "src/main/java/br/com/api/user/repository/UserRepository.java"
  - "src/main/java/br/com/api/user/resource/JwtResponse.java"
  - "src/main/java/br/com/api/user/resource/Token.java"
  - "src/main/java/br/com/api/user/utils/Utils.java"
